INSERT INTO Cities (city_name,city_postal_code) VALUES ('BAMBECQUE', '59046');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('BERGUES ', '59067');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('BIERNE', '59082');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('BISSEZEELE', '59083');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('BOLLEZEELE ', '59089');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('BOURBOURG  ', '59630');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('BRAY-DUNES ', '59123');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('BROUCKERQUE ', '59110');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('BROXEELE ', '59111');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('CAPPELLE-BROUCK ', '59130');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('CAPPELLE-LA-GRANDE ', '59180');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('COUDEKERQUE-BRANCHE ', '59210');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('CRAYWICK ', '59279');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('CROCHTE ', '59162');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('DUNKERQUE', '59140');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('DK FORT-MARDYCK ', '59430');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('DK GRANDE-SYNTHE ', '59271');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('DK MALO-LES-BAINS ', '59373');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('DK MARDYCK ', '59279');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('DK PETITE-SYNTHE', '59640');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('DK ROSENDAEL ', '59510');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('DK SAINT-POL-SUR-MER ', '59430');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('DRINCHAM ', '59182');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('ERINGHEM ', '59200');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('ESQUELBECQ ', '59470');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('GHYVELDE-LES MOERES ', '59254');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('GRAND-FORT-PHILIPPE ', '59153');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('GRAVELINES ', '59820');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('HERZEELE ', '59305');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('HOLQUE ', '59307');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('HONDSCHOOTE ', '59309');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('HOYMILLE ', '59319');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('KILLEM ', '59326');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('LEDERZEELE ', '59337');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('LEDRINGHEM ', '59338');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('LEFFRINCKOUCKE ', '59495');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('LOOBERGHE ', '59358');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('LOON-PLAGE ', '59279');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('MERCKEGHEM ', '59397');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('MILLAM  ', '59402');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('NIEURLET  ', '59433');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('OOST-CAPPEL ', '59448');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('PITGAM ', '59463');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('QUAËDYPRE ', '59478');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('REXPOËDE ', '59499');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('SAINT-GEORGES-SUR-L''AA', '59532');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('SAINT-MOMELIN ', '59538');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('SAINT-PIERRE-BROUCK ', '59539');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('SOCX ', '59570');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('SPYCKER ', '59380');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('STEENE ', '59579');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('TETEGHEM-COUDEKERQUE-VILLAGE ', '59229');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('UXEM ', '59605');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('VOLCKERINCKHOVE ', '59628');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('WARHEM ', '59641');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('WATTEN ', '59647');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('WEST-CAPPEL ', '59657');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('WORMHOUT ', '59663');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('WULVERDINGHE ', '59664');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('WYLDER ', '59665');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('ZEGERSCAPPEL ', '59666');
INSERT INTO Cities (city_name,city_postal_code) VALUES ('ZUYDCOOTE ', '59123');
